/* eslint-env node */
/* global console */

import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { execFileSync } from "node:child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read version from manifest.json
const manifestPath = path.join(__dirname, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
const pluginVersion = manifest.version;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const DEV_PLUGIN_PATH =
  process.env.DEV_PLUGIN_PATH ||
  path.join(
    process.env.HOME,
    "obsidian/Everything/.obsidian/plugins/granola-sync/main.js"
  );

// Regenerate src/services/embeddedKeyringBinaries.ts before each build so the
// bundle picks up the current @napi-rs/keyring binaries. The TS file is large
// (~8 MB of base64) and not committed — this keeps it fresh after `pnpm install`.
function regenerateEmbeddedBinaries() {
  console.log("Regenerating embedded keyring binaries…");
  execFileSync(
    process.execPath,
    [path.join(__dirname, "scripts/generateEmbeddedKeyringBinaries.mjs")],
    { stdio: "inherit" }
  );
}

function copyToDevPlugin() {
  if (prod) return;

  try {
    const outputPath = path.join(__dirname, "output/main.js");
    const stylesPath = path.join(__dirname, "styles.css");
    const targetDir = path.dirname(DEV_PLUGIN_PATH);
    const manifestTargetPath = path.join(targetDir, "manifest.json");
    const stylesTargetPath = path.join(targetDir, "styles.css");

    if (!fs.existsSync(targetDir)) {
      console.error(`Target directory does not exist: ${targetDir}`);
      return;
    }

    fs.copyFileSync(outputPath, DEV_PLUGIN_PATH);
    console.log(`✓ Copied main.js to ${DEV_PLUGIN_PATH}`);

    if (fs.existsSync(stylesPath)) {
      fs.copyFileSync(stylesPath, stylesTargetPath);
      console.log(`✓ Copied styles.css to ${stylesTargetPath}`);
    }

    const devManifest = { ...manifest, version: "1.0.0" };
    fs.writeFileSync(
      manifestTargetPath,
      `${JSON.stringify(devManifest, null, 2)}\n`,
      "utf-8"
    );
    console.log(`✓ Wrote dev manifest.json to ${manifestTargetPath}`);

    // Stale binaries previously copied via the per-platform node_modules path —
    // remove them so we don't end up with two keyring backends in the plugin dir.
    const staleNodeModules = path.join(targetDir, "node_modules");
    if (fs.existsSync(staleNodeModules)) {
      fs.rmSync(staleNodeModules, { recursive: true, force: true });
      console.log(`✓ Removed stale ${staleNodeModules}`);
    }
  } catch (error) {
    console.error(`Failed to copy to dev plugin directory: ${error.message}`);
  }
}

const copyPlugin = {
  name: "copy-to-dev-plugin",
  setup(build) {
    if (prod) return;
    build.onEnd(() => {
      copyToDevPlugin();
    });
  },
};

regenerateEmbeddedBinaries();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  define: {
    PLUGIN_VERSION: JSON.stringify(pluginVersion),
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "output/main.js",
  minify: prod,
  loader: { ".svg": "text" },
  plugins: [copyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.rebuild();
  await context.watch();
}
