import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read version from manifest.json
const manifestPath = path.join(__dirname, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
const pluginVersion = manifest.version;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const DEV_PLUGIN_PATH =
  process.env.DEV_PLUGIN_PATH ||
  path.join(
    process.env.HOME,
    "Documents/Obsidian Vault/.obsidian/plugins/obsidian-granola-sync/main.js"
  );

function copyToDevPlugin() {
  if (prod) return;

  try {
    const outputPath = path.join(__dirname, "output/main.js");
    const targetDir = path.dirname(DEV_PLUGIN_PATH);

    // Check if target directory exists
    if (!fs.existsSync(targetDir)) {
      console.error(`Target directory does not exist: ${targetDir}`);
      return;
    }

    // Copy the file
    fs.copyFileSync(outputPath, DEV_PLUGIN_PATH);
    console.log(`✓ Copied to ${DEV_PLUGIN_PATH}`);
  } catch (error) {
    console.error(`Failed to copy to dev plugin directory: ${error.message}`);
  }
}

// Plugin to copy file after build in development mode
const copyPlugin = {
  name: "copy-to-dev-plugin",
  setup(build) {
    if (prod) return;

    build.onEnd(() => {
      copyToDevPlugin();
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  define: {
    PLUGIN_VERSION: JSON.stringify(pluginVersion),
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "output/main.js",
  minify: prod,
  plugins: [copyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  // Initial build (plugin will copy automatically)
  await context.rebuild();

  // Watch for changes (plugin will copy on each rebuild)
  await context.watch();
}
