#!/usr/bin/env node
/**
 * Reads each Windows `@primno+dpapi.node` prebuilt binary installed by pnpm
 * and emits src/services/embeddedDpapiBinaries.ts with base64-encoded
 * contents.
 *
 * Same mechanism as scripts/generateEmbeddedKeyringBinaries.mjs: bundled into
 * main.js so the plugin can ship as a single file and still call DPAPI on
 * Windows to unwrap Granola's Local State key.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.join(__dirname, "..");

// `prebuildify` lays each native binary out at
// `prebuilds/<platform>-<arch>/@primno+dpapi.node`. The tag matches the
// `${process.platform}-${process.arch}` token we use to pick a binary at
// runtime.
const TARGETS = [
  { tag: "win32-x64", prebuildsDir: "win32-x64" },
  { tag: "win32-arm64", prebuildsDir: "win32-arm64" },
];

const BINARY_FILENAME = "@primno+dpapi.node";

function findDpapiBinary(prebuildsDir) {
  const filePath = path.join(
    repoRoot,
    "node_modules",
    "@primno",
    "dpapi",
    "prebuilds",
    prebuildsDir,
    BINARY_FILENAME
  );
  return fs.existsSync(filePath) ? filePath : null;
}

function readDpapiVersion() {
  const pkgJsonPath = path.join(
    repoRoot,
    "node_modules",
    "@primno",
    "dpapi",
    "package.json"
  );
  if (!fs.existsSync(pkgJsonPath)) return "unknown";
  return JSON.parse(fs.readFileSync(pkgJsonPath, "utf8")).version;
}

const dpapiVersion = readDpapiVersion();
const entries = [];
const missing = [];

for (const { tag, prebuildsDir } of TARGETS) {
  const filePath = findDpapiBinary(prebuildsDir);
  if (!filePath) {
    missing.push(tag);
    continue;
  }
  const data = fs.readFileSync(filePath);
  entries.push({ tag, base64: data.toString("base64"), size: data.length });
  console.log(`  ✓ ${tag.padEnd(20)} ${(data.length / 1024).toFixed(0).padStart(5)} KB`);
}

if (missing.length > 0) {
  console.error(
    `\n✗ Missing DPAPI binaries for: ${missing.join(", ")}\n  Run \`pnpm install\` to fetch @primno/dpapi prebuilds.`
  );
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/generateEmbeddedDpapiBinaries.mjs",
  "// DO NOT EDIT BY HAND.",
  "// @ts-nocheck",
  "/* eslint-disable */",
  "",
  `export const DPAPI_VERSION = ${JSON.stringify(dpapiVersion)};`,
  "",
  "export const EMBEDDED_DPAPI_BINARIES: Record<string, string> = {",
  ...entries.map(
    ({ tag, base64 }) => `  ${JSON.stringify(tag)}: ${JSON.stringify(base64)},`
  ),
  "};",
  "",
];

const outPath = path.join(
  repoRoot,
  "src",
  "services",
  "embeddedDpapiBinaries.ts"
);
fs.writeFileSync(outPath, lines.join("\n"));

const totalBytes = entries.reduce((s, e) => s + e.size, 0);
console.log(
  `\nWrote ${outPath} (${entries.length} platforms, ${(totalBytes / 1024).toFixed(0)} KB raw)`
);
