#!/usr/bin/env node
/**
 * Reads each platform `keyring.<tag>.node` binary that pnpm has installed
 * under node_modules/.pnpm and emits src/services/embeddedKeyringBinaries.ts
 * with base64-encoded contents.
 *
 * Bundled into main.js so the plugin can ship as a single file and still
 * decrypt Granola credentials via the OS keychain on every supported
 * platform.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.join(__dirname, "..");

// Each entry: { tag, pkg } where tag matches @napi-rs/keyring's runtime
// platform-arch token (used to pick the binary at load time) and pkg is the
// npm subpackage name under @napi-rs/.
const TARGETS = [
  { tag: "darwin-arm64", pkg: "keyring-darwin-arm64" },
  { tag: "darwin-x64", pkg: "keyring-darwin-x64" },
  { tag: "linux-x64-gnu", pkg: "keyring-linux-x64-gnu" },
  { tag: "win32-x64-msvc", pkg: "keyring-win32-x64-msvc" },
];

function findPnpmBinary(pkgName, filename) {
  const pnpmDir = path.join(repoRoot, "node_modules", ".pnpm");
  if (!fs.existsSync(pnpmDir)) return null;
  const entries = fs.readdirSync(pnpmDir);
  const match = entries.find((e) => e.startsWith(`@napi-rs+${pkgName}@`));
  if (!match) return null;
  const filePath = path.join(
    pnpmDir,
    match,
    "node_modules",
    "@napi-rs",
    pkgName,
    filename
  );
  return fs.existsSync(filePath) ? filePath : null;
}

function readKeyringVersion() {
  const pkgJsonPath = path.join(
    repoRoot,
    "node_modules",
    "@napi-rs",
    "keyring",
    "package.json"
  );
  if (!fs.existsSync(pkgJsonPath)) return "unknown";
  return JSON.parse(fs.readFileSync(pkgJsonPath, "utf8")).version;
}

const keyringVersion = readKeyringVersion();
const entries = [];
const missing = [];

for (const { tag, pkg } of TARGETS) {
  const filename = `keyring.${tag}.node`;
  const filePath = findPnpmBinary(pkg, filename);
  if (!filePath) {
    missing.push(tag);
    continue;
  }
  const data = fs.readFileSync(filePath);
  entries.push({ tag, base64: data.toString("base64"), size: data.length });
  console.log(`  ✓ ${tag.padEnd(20)} ${(data.length / 1024).toFixed(0).padStart(5)} KB`);
}

if (missing.length > 0) {
  console.error(
    `\n✗ Missing binaries for: ${missing.join(", ")}\n  Run \`pnpm install\` to fetch all platform packages.`
  );
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/generateEmbeddedKeyringBinaries.mjs",
  "// DO NOT EDIT BY HAND.",
  "// @ts-nocheck",
  "/* eslint-disable */",
  "",
  `export const KEYRING_VERSION = ${JSON.stringify(keyringVersion)};`,
  "",
  "export const EMBEDDED_KEYRING_BINARIES: Record<string, string> = {",
  ...entries.map(
    ({ tag, base64 }) => `  ${JSON.stringify(tag)}: ${JSON.stringify(base64)},`
  ),
  "};",
  "",
];

const outPath = path.join(
  repoRoot,
  "src",
  "services",
  "embeddedKeyringBinaries.ts"
);
fs.writeFileSync(outPath, lines.join("\n"));

const totalBytes = entries.reduce((s, e) => s + e.size, 0);
console.log(
  `\nWrote ${outPath} (${entries.length} platforms, ${(totalBytes / 1024 / 1024).toFixed(2)} MB raw)`
);
